<!DOCTYPE html>
<html lang="ru">
<head>
    <title>ADMIN - Панель</title>
    <style>
        body {margin: 20px}
    </style>
</head>
<body>
<h2 style="text-align: center">Панель администратора</h2>
<h4 style="text-align: center">
    <a href="/">Главная страница</a> ||
    <a href="/admin/users">Список всех пользователей</a> ||
    <a href="/admin/polls">Список всех опросов</a>
</h4>
</body>
</html>